# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: config.diki.gardener.cloud/v1alpha1
kind: DikiOperatorConfiguration

# log:
#   level: info
#   format: json

# controllers:
#   complianceScan:
#     syncPeriod: 1h
#     baseOptions:
#       configMapRef:
#         name: diki-base-options
#     dikiRunner:
#       podCompletionTimeout: 10m
#       namespace: kube-system
#       targetKubeconfig:
#         secretRef:
#           name: target-cluster-kubeconfig
#         tokenSecretRef:
#           name: target-cluster-token
#         mountPath: /var/run/secrets/target-cluster/kubeconfig
#     defaultOutputs:
#     - name: central-reporting
#       type: ConfigMap
#       config:
#         namespace: kube-system
#         namePrefix: default-report-
# server:
#   healthProbes:
#     port: 8081
#   metrics:
#     port: 8080
# leaderElection:
#   resourceName: diki-operator-leader-election
#   resourceNamespace: kube-system
#   leaderElect: true
#   leaseDuration: 15s
#   renewDeadline: 10s
#   retryPeriod: 2s
#   resourceLock: leases
