apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: diki-operator
build:
  artifacts:
    - image: local-skaffold/diki-operator
      ko:
        dependencies:
          paths:
            - cmd/diki-operator
            - cmd/diki-operator/app
            - imagevector
            - imagevector/images.yaml
            - internal/reconciler/compliancescan
            - internal/reconciler/scheduledcompliancescan
            - internal/utils
            - pkg/apis/config/v1alpha1
            - pkg/apis/config/v1alpha1/validation
            - pkg/apis/diki
            - pkg/apis/diki/install
            - pkg/apis/diki/v1alpha1
            - pkg/apis/diki/v1alpha1/helper
            - pkg/apis/dikiexporter/v1alpha1
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/diki-operator
    - image: local-skaffold/diki-exporter
      ko:
        dependencies:
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/diki-exporter
  tagPolicy:
    customTemplate:
      template: '{{.version}}-{{.sha}}'
      components:
        - name: sha
          gitCommit:
            variant: AbbrevCommitSha
deploy:
  helm:
    releases:
      - name: diki-operator
        chartPath: charts/diki/diki-operator
        valuesFiles:
          - charts/diki/diki-operator/values.yaml
        namespace: kube-system
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_diki_operator}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_diki_operator}}@{{.IMAGE_DIGEST_local_skaffold_diki_operator}}'
          imageVectorOverwrite: |
            images:
            - name: diki-exporter
              repository: {{.IMAGE_REPO_local_skaffold_diki_exporter}}
              tag: {{.IMAGE_TAG_local_skaffold_diki_exporter}}
        createNamespace: false
        wait: true
profiles:
  - name: shoot
    build:
      local:
        push: true
      insecureRegistries:
        - registry.local.gardener.cloud:5001
      artifacts:
        - image: registry.local.gardener.cloud:5001/diki-operator
          ko:
            dependencies:
              paths:
                - cmd/diki-operator
                - cmd/diki-operator/app
                - imagevector
                - imagevector/images.yaml
                - internal/reconciler/compliancescan
                - internal/utils
                - pkg/apis/config/v1alpha1
                - pkg/apis/config/v1alpha1/validation
                - pkg/apis/diki
                - pkg/apis/diki/install
                - pkg/apis/diki/v1alpha1
                - pkg/apis/diki/v1alpha1/helper
                - pkg/apis/dikiexporter/v1alpha1
                - VERSION
            ldflags:
              - '{{.LD_FLAGS}}'
            main: ./cmd/diki-operator
        - image: registry.local.gardener.cloud:5001/diki-exporter
          ko:
            dependencies:
            ldflags:
              - '{{.LD_FLAGS}}'
            main: ./cmd/diki-exporter
      tagPolicy:
        customTemplate:
          template: '{{.version}}-{{.sha}}'
          components:
            - name: sha
              gitCommit:
                variant: AbbrevCommitSha
    deploy:
      kubeContext: garden-local--local-external
      helm:
        releases:
          - name: diki-operator
            chartPath: charts/diki/diki-operator
            valuesFiles:
              - charts/diki/diki-operator/values.yaml
            namespace: kube-system
            setValueTemplates:
              image.repository: '{{.IMAGE_REPO_registry_local_gardener_cloud_5001_diki_operator}}'
              image.tag: '{{.IMAGE_TAG_registry_local_gardener_cloud_5001_diki_operator}}@{{.IMAGE_DIGEST_registry_local_gardener_cloud_5001_diki_operator}}'
              imageVectorOverwrite: |
                images:
                - name: diki-exporter
                  repository: {{.IMAGE_REPO_registry_local_gardener_cloud_5001_diki_exporter}}
                  tag: {{.IMAGE_TAG_registry_local_gardener_cloud_5001_diki_exporter}}
            createNamespace: false
            wait: true
