# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: diki-operator
  namespace: shoot--local--local
  labels:
    app.kubernetes.io/name: diki-operator
data:
  config.yaml: |
    apiVersion: config.diki.gardener.cloud/v1alpha1
    kind: DikiOperatorConfiguration
    log:
        level: info
        format: json
    controllers:
      complianceScan:
        syncPeriod: 1h
        dikiRunner:
          waitInterval: 5s
          podCompletionTimeout: 10m
          execTimeout: 30s
          namespace: shoot--local--local
          kubeconfig: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig-runner/kubeconfig
          labels:
            networking.gardener.cloud/to-blocked-cidrs: allowed
            networking.gardener.cloud/to-dns: allowed
            networking.gardener.cloud/to-private-networks: allowed
            networking.gardener.cloud/to-public-networks: allowed
            networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    server:
      healthProbes:
        port: 8081
      metrics:
        port: 8080
    leaderElection:
      resourceName: diki-operator-leader-election
      resourceNamespace: kube-system
      leaderElect: true
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
      resourceLock: leases
