apiVersion: v1
data:
kind: Secret
metadata:
  annotations:
    serviceaccount.resources.gardener.cloud/name: diki-runner
    serviceaccount.resources.gardener.cloud/namespace: kube-system
  labels:
    resources.gardener.cloud/class: shoot
    resources.gardener.cloud/purpose: token-requestor
  name: shoot-access-diki-runner
  namespace: shoot--local--local
type: Opaque