//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	diki "github.com/gardener/diki-operator/pkg/apis/diki"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ComplianceScan)(nil), (*diki.ComplianceScan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceScan_To_diki_ComplianceScan(a.(*ComplianceScan), b.(*diki.ComplianceScan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceScan)(nil), (*ComplianceScan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceScan_To_v1alpha1_ComplianceScan(a.(*diki.ComplianceScan), b.(*ComplianceScan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceScanList)(nil), (*diki.ComplianceScanList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceScanList_To_diki_ComplianceScanList(a.(*ComplianceScanList), b.(*diki.ComplianceScanList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceScanList)(nil), (*ComplianceScanList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceScanList_To_v1alpha1_ComplianceScanList(a.(*diki.ComplianceScanList), b.(*ComplianceScanList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceScanSpec)(nil), (*diki.ComplianceScanSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceScanSpec_To_diki_ComplianceScanSpec(a.(*ComplianceScanSpec), b.(*diki.ComplianceScanSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceScanSpec)(nil), (*ComplianceScanSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceScanSpec_To_v1alpha1_ComplianceScanSpec(a.(*diki.ComplianceScanSpec), b.(*ComplianceScanSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceScanStatus)(nil), (*diki.ComplianceScanStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceScanStatus_To_diki_ComplianceScanStatus(a.(*ComplianceScanStatus), b.(*diki.ComplianceScanStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceScanStatus)(nil), (*ComplianceScanStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceScanStatus_To_v1alpha1_ComplianceScanStatus(a.(*diki.ComplianceScanStatus), b.(*ComplianceScanStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceScanTemplate)(nil), (*diki.ComplianceScanTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceScanTemplate_To_diki_ComplianceScanTemplate(a.(*ComplianceScanTemplate), b.(*diki.ComplianceScanTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceScanTemplate)(nil), (*ComplianceScanTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceScanTemplate_To_v1alpha1_ComplianceScanTemplate(a.(*diki.ComplianceScanTemplate), b.(*ComplianceScanTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Condition)(nil), (*diki.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Condition_To_diki_Condition(a.(*Condition), b.(*diki.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Condition_To_v1alpha1_Condition(a.(*diki.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigMapOutput)(nil), (*diki.ConfigMapOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigMapOutput_To_diki_ConfigMapOutput(a.(*ConfigMapOutput), b.(*diki.ConfigMapOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ConfigMapOutput)(nil), (*ConfigMapOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ConfigMapOutput_To_v1alpha1_ConfigMapOutput(a.(*diki.ConfigMapOutput), b.(*ConfigMapOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Options)(nil), (*diki.Options)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Options_To_diki_Options(a.(*Options), b.(*diki.Options), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Options)(nil), (*Options)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Options_To_v1alpha1_Options(a.(*diki.Options), b.(*Options), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OptionsConfigMapRef)(nil), (*diki.OptionsConfigMapRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef(a.(*OptionsConfigMapRef), b.(*diki.OptionsConfigMapRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.OptionsConfigMapRef)(nil), (*OptionsConfigMapRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef(a.(*diki.OptionsConfigMapRef), b.(*OptionsConfigMapRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Output)(nil), (*diki.Output)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Output_To_diki_Output(a.(*Output), b.(*diki.Output), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Output)(nil), (*Output)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Output_To_v1alpha1_Output(a.(*diki.Output), b.(*Output), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OutputStatus)(nil), (*diki.OutputStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OutputStatus_To_diki_OutputStatus(a.(*OutputStatus), b.(*diki.OutputStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.OutputStatus)(nil), (*OutputStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_OutputStatus_To_v1alpha1_OutputStatus(a.(*diki.OutputStatus), b.(*OutputStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PostgresOutput)(nil), (*diki.PostgresOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PostgresOutput_To_diki_PostgresOutput(a.(*PostgresOutput), b.(*diki.PostgresOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.PostgresOutput)(nil), (*PostgresOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_PostgresOutput_To_v1alpha1_PostgresOutput(a.(*diki.PostgresOutput), b.(*PostgresOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReportOutput)(nil), (*diki.ReportOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReportOutput_To_diki_ReportOutput(a.(*ReportOutput), b.(*diki.ReportOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ReportOutput)(nil), (*ReportOutput)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ReportOutput_To_v1alpha1_ReportOutput(a.(*diki.ReportOutput), b.(*ReportOutput), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReportOutputList)(nil), (*diki.ReportOutputList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReportOutputList_To_diki_ReportOutputList(a.(*ReportOutputList), b.(*diki.ReportOutputList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ReportOutputList)(nil), (*ReportOutputList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ReportOutputList_To_v1alpha1_ReportOutputList(a.(*diki.ReportOutputList), b.(*ReportOutputList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReportOutputRef)(nil), (*diki.ReportOutputRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReportOutputRef_To_diki_ReportOutputRef(a.(*ReportOutputRef), b.(*diki.ReportOutputRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ReportOutputRef)(nil), (*ReportOutputRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ReportOutputRef_To_v1alpha1_ReportOutputRef(a.(*diki.ReportOutputRef), b.(*ReportOutputRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReportOutputSpec)(nil), (*diki.ReportOutputSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReportOutputSpec_To_diki_ReportOutputSpec(a.(*ReportOutputSpec), b.(*diki.ReportOutputSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ReportOutputSpec)(nil), (*ReportOutputSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ReportOutputSpec_To_v1alpha1_ReportOutputSpec(a.(*diki.ReportOutputSpec), b.(*ReportOutputSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Rule)(nil), (*diki.Rule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Rule_To_diki_Rule(a.(*Rule), b.(*diki.Rule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Rule)(nil), (*Rule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Rule_To_v1alpha1_Rule(a.(*diki.Rule), b.(*Rule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesFindings)(nil), (*diki.RulesFindings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesFindings_To_diki_RulesFindings(a.(*RulesFindings), b.(*diki.RulesFindings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesFindings)(nil), (*RulesFindings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesFindings_To_v1alpha1_RulesFindings(a.(*diki.RulesFindings), b.(*RulesFindings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesResults)(nil), (*diki.RulesResults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesResults_To_diki_RulesResults(a.(*RulesResults), b.(*diki.RulesResults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesResults)(nil), (*RulesResults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesResults_To_v1alpha1_RulesResults(a.(*diki.RulesResults), b.(*RulesResults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesSummary)(nil), (*diki.RulesSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesSummary_To_diki_RulesSummary(a.(*RulesSummary), b.(*diki.RulesSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesSummary)(nil), (*RulesSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesSummary_To_v1alpha1_RulesSummary(a.(*diki.RulesSummary), b.(*RulesSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesetConfig)(nil), (*diki.RulesetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(a.(*RulesetConfig), b.(*diki.RulesetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesetConfig)(nil), (*RulesetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(a.(*diki.RulesetConfig), b.(*RulesetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesetOptions)(nil), (*diki.RulesetOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesetOptions_To_diki_RulesetOptions(a.(*RulesetOptions), b.(*diki.RulesetOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesetOptions)(nil), (*RulesetOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesetOptions_To_v1alpha1_RulesetOptions(a.(*diki.RulesetOptions), b.(*RulesetOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesetSummary)(nil), (*diki.RulesetSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(a.(*RulesetSummary), b.(*diki.RulesetSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesetSummary)(nil), (*RulesetSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(a.(*diki.RulesetSummary), b.(*RulesetSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ScheduledComplianceScan)(nil), (*diki.ScheduledComplianceScan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ScheduledComplianceScan_To_diki_ScheduledComplianceScan(a.(*ScheduledComplianceScan), b.(*diki.ScheduledComplianceScan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ScheduledComplianceScan)(nil), (*ScheduledComplianceScan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ScheduledComplianceScan_To_v1alpha1_ScheduledComplianceScan(a.(*diki.ScheduledComplianceScan), b.(*ScheduledComplianceScan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ScheduledComplianceScanList)(nil), (*diki.ScheduledComplianceScanList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ScheduledComplianceScanList_To_diki_ScheduledComplianceScanList(a.(*ScheduledComplianceScanList), b.(*diki.ScheduledComplianceScanList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ScheduledComplianceScanList)(nil), (*ScheduledComplianceScanList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ScheduledComplianceScanList_To_v1alpha1_ScheduledComplianceScanList(a.(*diki.ScheduledComplianceScanList), b.(*ScheduledComplianceScanList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ScheduledComplianceScanSpec)(nil), (*diki.ScheduledComplianceScanSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ScheduledComplianceScanSpec_To_diki_ScheduledComplianceScanSpec(a.(*ScheduledComplianceScanSpec), b.(*diki.ScheduledComplianceScanSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ScheduledComplianceScanSpec)(nil), (*ScheduledComplianceScanSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ScheduledComplianceScanSpec_To_v1alpha1_ScheduledComplianceScanSpec(a.(*diki.ScheduledComplianceScanSpec), b.(*ScheduledComplianceScanSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ScheduledComplianceScanStatus)(nil), (*diki.ScheduledComplianceScanStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ScheduledComplianceScanStatus_To_diki_ScheduledComplianceScanStatus(a.(*ScheduledComplianceScanStatus), b.(*diki.ScheduledComplianceScanStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ScheduledComplianceScanStatus)(nil), (*ScheduledComplianceScanStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ScheduledComplianceScanStatus_To_v1alpha1_ScheduledComplianceScanStatus(a.(*diki.ScheduledComplianceScanStatus), b.(*ScheduledComplianceScanStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ComplianceScan_To_diki_ComplianceScan(in *ComplianceScan, out *diki.ComplianceScan, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ComplianceScanSpec_To_diki_ComplianceScanSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ComplianceScanStatus_To_diki_ComplianceScanStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ComplianceScan_To_diki_ComplianceScan is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceScan_To_diki_ComplianceScan(in *ComplianceScan, out *diki.ComplianceScan, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceScan_To_diki_ComplianceScan(in, out, s)
}

func autoConvert_diki_ComplianceScan_To_v1alpha1_ComplianceScan(in *diki.ComplianceScan, out *ComplianceScan, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_diki_ComplianceScanSpec_To_v1alpha1_ComplianceScanSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_diki_ComplianceScanStatus_To_v1alpha1_ComplianceScanStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_ComplianceScan_To_v1alpha1_ComplianceScan is an autogenerated conversion function.
func Convert_diki_ComplianceScan_To_v1alpha1_ComplianceScan(in *diki.ComplianceScan, out *ComplianceScan, s conversion.Scope) error {
	return autoConvert_diki_ComplianceScan_To_v1alpha1_ComplianceScan(in, out, s)
}

func autoConvert_v1alpha1_ComplianceScanList_To_diki_ComplianceScanList(in *ComplianceScanList, out *diki.ComplianceScanList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]diki.ComplianceScan)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ComplianceScanList_To_diki_ComplianceScanList is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceScanList_To_diki_ComplianceScanList(in *ComplianceScanList, out *diki.ComplianceScanList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceScanList_To_diki_ComplianceScanList(in, out, s)
}

func autoConvert_diki_ComplianceScanList_To_v1alpha1_ComplianceScanList(in *diki.ComplianceScanList, out *ComplianceScanList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ComplianceScan)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_diki_ComplianceScanList_To_v1alpha1_ComplianceScanList is an autogenerated conversion function.
func Convert_diki_ComplianceScanList_To_v1alpha1_ComplianceScanList(in *diki.ComplianceScanList, out *ComplianceScanList, s conversion.Scope) error {
	return autoConvert_diki_ComplianceScanList_To_v1alpha1_ComplianceScanList(in, out, s)
}

func autoConvert_v1alpha1_ComplianceScanSpec_To_diki_ComplianceScanSpec(in *ComplianceScanSpec, out *diki.ComplianceScanSpec, s conversion.Scope) error {
	out.Rulesets = *(*[]diki.RulesetConfig)(unsafe.Pointer(&in.Rulesets))
	out.Outputs = *(*[]diki.ReportOutputRef)(unsafe.Pointer(&in.Outputs))
	return nil
}

// Convert_v1alpha1_ComplianceScanSpec_To_diki_ComplianceScanSpec is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceScanSpec_To_diki_ComplianceScanSpec(in *ComplianceScanSpec, out *diki.ComplianceScanSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceScanSpec_To_diki_ComplianceScanSpec(in, out, s)
}

func autoConvert_diki_ComplianceScanSpec_To_v1alpha1_ComplianceScanSpec(in *diki.ComplianceScanSpec, out *ComplianceScanSpec, s conversion.Scope) error {
	out.Rulesets = *(*[]RulesetConfig)(unsafe.Pointer(&in.Rulesets))
	out.Outputs = *(*[]ReportOutputRef)(unsafe.Pointer(&in.Outputs))
	return nil
}

// Convert_diki_ComplianceScanSpec_To_v1alpha1_ComplianceScanSpec is an autogenerated conversion function.
func Convert_diki_ComplianceScanSpec_To_v1alpha1_ComplianceScanSpec(in *diki.ComplianceScanSpec, out *ComplianceScanSpec, s conversion.Scope) error {
	return autoConvert_diki_ComplianceScanSpec_To_v1alpha1_ComplianceScanSpec(in, out, s)
}

func autoConvert_v1alpha1_ComplianceScanStatus_To_diki_ComplianceScanStatus(in *ComplianceScanStatus, out *diki.ComplianceScanStatus, s conversion.Scope) error {
	out.Conditions = *(*[]diki.Condition)(unsafe.Pointer(&in.Conditions))
	out.Phase = diki.ComplianceScanPhase(in.Phase)
	out.Rulesets = *(*[]diki.RulesetSummary)(unsafe.Pointer(&in.Rulesets))
	out.Outputs = *(*[]diki.OutputStatus)(unsafe.Pointer(&in.Outputs))
	return nil
}

// Convert_v1alpha1_ComplianceScanStatus_To_diki_ComplianceScanStatus is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceScanStatus_To_diki_ComplianceScanStatus(in *ComplianceScanStatus, out *diki.ComplianceScanStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceScanStatus_To_diki_ComplianceScanStatus(in, out, s)
}

func autoConvert_diki_ComplianceScanStatus_To_v1alpha1_ComplianceScanStatus(in *diki.ComplianceScanStatus, out *ComplianceScanStatus, s conversion.Scope) error {
	out.Conditions = *(*[]Condition)(unsafe.Pointer(&in.Conditions))
	out.Phase = ComplianceScanPhase(in.Phase)
	out.Rulesets = *(*[]RulesetSummary)(unsafe.Pointer(&in.Rulesets))
	out.Outputs = *(*[]OutputStatus)(unsafe.Pointer(&in.Outputs))
	return nil
}

// Convert_diki_ComplianceScanStatus_To_v1alpha1_ComplianceScanStatus is an autogenerated conversion function.
func Convert_diki_ComplianceScanStatus_To_v1alpha1_ComplianceScanStatus(in *diki.ComplianceScanStatus, out *ComplianceScanStatus, s conversion.Scope) error {
	return autoConvert_diki_ComplianceScanStatus_To_v1alpha1_ComplianceScanStatus(in, out, s)
}

func autoConvert_v1alpha1_ComplianceScanTemplate_To_diki_ComplianceScanTemplate(in *ComplianceScanTemplate, out *diki.ComplianceScanTemplate, s conversion.Scope) error {
	if err := Convert_v1alpha1_ComplianceScanSpec_To_diki_ComplianceScanSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ComplianceScanTemplate_To_diki_ComplianceScanTemplate is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceScanTemplate_To_diki_ComplianceScanTemplate(in *ComplianceScanTemplate, out *diki.ComplianceScanTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceScanTemplate_To_diki_ComplianceScanTemplate(in, out, s)
}

func autoConvert_diki_ComplianceScanTemplate_To_v1alpha1_ComplianceScanTemplate(in *diki.ComplianceScanTemplate, out *ComplianceScanTemplate, s conversion.Scope) error {
	if err := Convert_diki_ComplianceScanSpec_To_v1alpha1_ComplianceScanSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_ComplianceScanTemplate_To_v1alpha1_ComplianceScanTemplate is an autogenerated conversion function.
func Convert_diki_ComplianceScanTemplate_To_v1alpha1_ComplianceScanTemplate(in *diki.ComplianceScanTemplate, out *ComplianceScanTemplate, s conversion.Scope) error {
	return autoConvert_diki_ComplianceScanTemplate_To_v1alpha1_ComplianceScanTemplate(in, out, s)
}

func autoConvert_v1alpha1_Condition_To_diki_Condition(in *Condition, out *diki.Condition, s conversion.Scope) error {
	out.Type = diki.ConditionType(in.Type)
	out.Status = diki.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_Condition_To_diki_Condition is an autogenerated conversion function.
func Convert_v1alpha1_Condition_To_diki_Condition(in *Condition, out *diki.Condition, s conversion.Scope) error {
	return autoConvert_v1alpha1_Condition_To_diki_Condition(in, out, s)
}

func autoConvert_diki_Condition_To_v1alpha1_Condition(in *diki.Condition, out *Condition, s conversion.Scope) error {
	out.Type = ConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_diki_Condition_To_v1alpha1_Condition is an autogenerated conversion function.
func Convert_diki_Condition_To_v1alpha1_Condition(in *diki.Condition, out *Condition, s conversion.Scope) error {
	return autoConvert_diki_Condition_To_v1alpha1_Condition(in, out, s)
}

func autoConvert_v1alpha1_ConfigMapOutput_To_diki_ConfigMapOutput(in *ConfigMapOutput, out *diki.ConfigMapOutput, s conversion.Scope) error {
	out.Namespace = (*string)(unsafe.Pointer(in.Namespace))
	out.NamePrefix = (*string)(unsafe.Pointer(in.NamePrefix))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	return nil
}

// Convert_v1alpha1_ConfigMapOutput_To_diki_ConfigMapOutput is an autogenerated conversion function.
func Convert_v1alpha1_ConfigMapOutput_To_diki_ConfigMapOutput(in *ConfigMapOutput, out *diki.ConfigMapOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigMapOutput_To_diki_ConfigMapOutput(in, out, s)
}

func autoConvert_diki_ConfigMapOutput_To_v1alpha1_ConfigMapOutput(in *diki.ConfigMapOutput, out *ConfigMapOutput, s conversion.Scope) error {
	out.Namespace = (*string)(unsafe.Pointer(in.Namespace))
	out.NamePrefix = (*string)(unsafe.Pointer(in.NamePrefix))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	return nil
}

// Convert_diki_ConfigMapOutput_To_v1alpha1_ConfigMapOutput is an autogenerated conversion function.
func Convert_diki_ConfigMapOutput_To_v1alpha1_ConfigMapOutput(in *diki.ConfigMapOutput, out *ConfigMapOutput, s conversion.Scope) error {
	return autoConvert_diki_ConfigMapOutput_To_v1alpha1_ConfigMapOutput(in, out, s)
}

func autoConvert_v1alpha1_Options_To_diki_Options(in *Options, out *diki.Options, s conversion.Scope) error {
	out.ConfigMapRef = (*diki.OptionsConfigMapRef)(unsafe.Pointer(in.ConfigMapRef))
	return nil
}

// Convert_v1alpha1_Options_To_diki_Options is an autogenerated conversion function.
func Convert_v1alpha1_Options_To_diki_Options(in *Options, out *diki.Options, s conversion.Scope) error {
	return autoConvert_v1alpha1_Options_To_diki_Options(in, out, s)
}

func autoConvert_diki_Options_To_v1alpha1_Options(in *diki.Options, out *Options, s conversion.Scope) error {
	out.ConfigMapRef = (*OptionsConfigMapRef)(unsafe.Pointer(in.ConfigMapRef))
	return nil
}

// Convert_diki_Options_To_v1alpha1_Options is an autogenerated conversion function.
func Convert_diki_Options_To_v1alpha1_Options(in *diki.Options, out *Options, s conversion.Scope) error {
	return autoConvert_diki_Options_To_v1alpha1_Options(in, out, s)
}

func autoConvert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef(in *OptionsConfigMapRef, out *diki.OptionsConfigMapRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Key = (*string)(unsafe.Pointer(in.Key))
	return nil
}

// Convert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef is an autogenerated conversion function.
func Convert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef(in *OptionsConfigMapRef, out *diki.OptionsConfigMapRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef(in, out, s)
}

func autoConvert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef(in *diki.OptionsConfigMapRef, out *OptionsConfigMapRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Key = (*string)(unsafe.Pointer(in.Key))
	return nil
}

// Convert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef is an autogenerated conversion function.
func Convert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef(in *diki.OptionsConfigMapRef, out *OptionsConfigMapRef, s conversion.Scope) error {
	return autoConvert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef(in, out, s)
}

func autoConvert_v1alpha1_Output_To_diki_Output(in *Output, out *diki.Output, s conversion.Scope) error {
	out.ConfigMap = (*diki.ConfigMapOutput)(unsafe.Pointer(in.ConfigMap))
	out.Postgres = (*diki.PostgresOutput)(unsafe.Pointer(in.Postgres))
	return nil
}

// Convert_v1alpha1_Output_To_diki_Output is an autogenerated conversion function.
func Convert_v1alpha1_Output_To_diki_Output(in *Output, out *diki.Output, s conversion.Scope) error {
	return autoConvert_v1alpha1_Output_To_diki_Output(in, out, s)
}

func autoConvert_diki_Output_To_v1alpha1_Output(in *diki.Output, out *Output, s conversion.Scope) error {
	out.ConfigMap = (*ConfigMapOutput)(unsafe.Pointer(in.ConfigMap))
	out.Postgres = (*PostgresOutput)(unsafe.Pointer(in.Postgres))
	return nil
}

// Convert_diki_Output_To_v1alpha1_Output is an autogenerated conversion function.
func Convert_diki_Output_To_v1alpha1_Output(in *diki.Output, out *Output, s conversion.Scope) error {
	return autoConvert_diki_Output_To_v1alpha1_Output(in, out, s)
}

func autoConvert_v1alpha1_OutputStatus_To_diki_OutputStatus(in *OutputStatus, out *diki.OutputStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ReportOutputRef_To_diki_ReportOutputRef(&in.ReportOutputRef, &out.ReportOutputRef, s); err != nil {
		return err
	}
	out.Phase = diki.OutputStatusPhase(in.Phase)
	out.Details = in.Details
	return nil
}

// Convert_v1alpha1_OutputStatus_To_diki_OutputStatus is an autogenerated conversion function.
func Convert_v1alpha1_OutputStatus_To_diki_OutputStatus(in *OutputStatus, out *diki.OutputStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_OutputStatus_To_diki_OutputStatus(in, out, s)
}

func autoConvert_diki_OutputStatus_To_v1alpha1_OutputStatus(in *diki.OutputStatus, out *OutputStatus, s conversion.Scope) error {
	if err := Convert_diki_ReportOutputRef_To_v1alpha1_ReportOutputRef(&in.ReportOutputRef, &out.ReportOutputRef, s); err != nil {
		return err
	}
	out.Phase = OutputStatusPhase(in.Phase)
	out.Details = in.Details
	return nil
}

// Convert_diki_OutputStatus_To_v1alpha1_OutputStatus is an autogenerated conversion function.
func Convert_diki_OutputStatus_To_v1alpha1_OutputStatus(in *diki.OutputStatus, out *OutputStatus, s conversion.Scope) error {
	return autoConvert_diki_OutputStatus_To_v1alpha1_OutputStatus(in, out, s)
}

func autoConvert_v1alpha1_PostgresOutput_To_diki_PostgresOutput(in *PostgresOutput, out *diki.PostgresOutput, s conversion.Scope) error {
	out.ConnectionString = in.ConnectionString
	out.TableName = in.TableName
	return nil
}

// Convert_v1alpha1_PostgresOutput_To_diki_PostgresOutput is an autogenerated conversion function.
func Convert_v1alpha1_PostgresOutput_To_diki_PostgresOutput(in *PostgresOutput, out *diki.PostgresOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_PostgresOutput_To_diki_PostgresOutput(in, out, s)
}

func autoConvert_diki_PostgresOutput_To_v1alpha1_PostgresOutput(in *diki.PostgresOutput, out *PostgresOutput, s conversion.Scope) error {
	out.ConnectionString = in.ConnectionString
	out.TableName = in.TableName
	return nil
}

// Convert_diki_PostgresOutput_To_v1alpha1_PostgresOutput is an autogenerated conversion function.
func Convert_diki_PostgresOutput_To_v1alpha1_PostgresOutput(in *diki.PostgresOutput, out *PostgresOutput, s conversion.Scope) error {
	return autoConvert_diki_PostgresOutput_To_v1alpha1_PostgresOutput(in, out, s)
}

func autoConvert_v1alpha1_ReportOutput_To_diki_ReportOutput(in *ReportOutput, out *diki.ReportOutput, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ReportOutputSpec_To_diki_ReportOutputSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReportOutput_To_diki_ReportOutput is an autogenerated conversion function.
func Convert_v1alpha1_ReportOutput_To_diki_ReportOutput(in *ReportOutput, out *diki.ReportOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReportOutput_To_diki_ReportOutput(in, out, s)
}

func autoConvert_diki_ReportOutput_To_v1alpha1_ReportOutput(in *diki.ReportOutput, out *ReportOutput, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_diki_ReportOutputSpec_To_v1alpha1_ReportOutputSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_ReportOutput_To_v1alpha1_ReportOutput is an autogenerated conversion function.
func Convert_diki_ReportOutput_To_v1alpha1_ReportOutput(in *diki.ReportOutput, out *ReportOutput, s conversion.Scope) error {
	return autoConvert_diki_ReportOutput_To_v1alpha1_ReportOutput(in, out, s)
}

func autoConvert_v1alpha1_ReportOutputList_To_diki_ReportOutputList(in *ReportOutputList, out *diki.ReportOutputList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]diki.ReportOutput)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ReportOutputList_To_diki_ReportOutputList is an autogenerated conversion function.
func Convert_v1alpha1_ReportOutputList_To_diki_ReportOutputList(in *ReportOutputList, out *diki.ReportOutputList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReportOutputList_To_diki_ReportOutputList(in, out, s)
}

func autoConvert_diki_ReportOutputList_To_v1alpha1_ReportOutputList(in *diki.ReportOutputList, out *ReportOutputList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ReportOutput)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_diki_ReportOutputList_To_v1alpha1_ReportOutputList is an autogenerated conversion function.
func Convert_diki_ReportOutputList_To_v1alpha1_ReportOutputList(in *diki.ReportOutputList, out *ReportOutputList, s conversion.Scope) error {
	return autoConvert_diki_ReportOutputList_To_v1alpha1_ReportOutputList(in, out, s)
}

func autoConvert_v1alpha1_ReportOutputRef_To_diki_ReportOutputRef(in *ReportOutputRef, out *diki.ReportOutputRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ReportOutputRef_To_diki_ReportOutputRef is an autogenerated conversion function.
func Convert_v1alpha1_ReportOutputRef_To_diki_ReportOutputRef(in *ReportOutputRef, out *diki.ReportOutputRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReportOutputRef_To_diki_ReportOutputRef(in, out, s)
}

func autoConvert_diki_ReportOutputRef_To_v1alpha1_ReportOutputRef(in *diki.ReportOutputRef, out *ReportOutputRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_diki_ReportOutputRef_To_v1alpha1_ReportOutputRef is an autogenerated conversion function.
func Convert_diki_ReportOutputRef_To_v1alpha1_ReportOutputRef(in *diki.ReportOutputRef, out *ReportOutputRef, s conversion.Scope) error {
	return autoConvert_diki_ReportOutputRef_To_v1alpha1_ReportOutputRef(in, out, s)
}

func autoConvert_v1alpha1_ReportOutputSpec_To_diki_ReportOutputSpec(in *ReportOutputSpec, out *diki.ReportOutputSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_Output_To_diki_Output(&in.Output, &out.Output, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReportOutputSpec_To_diki_ReportOutputSpec is an autogenerated conversion function.
func Convert_v1alpha1_ReportOutputSpec_To_diki_ReportOutputSpec(in *ReportOutputSpec, out *diki.ReportOutputSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReportOutputSpec_To_diki_ReportOutputSpec(in, out, s)
}

func autoConvert_diki_ReportOutputSpec_To_v1alpha1_ReportOutputSpec(in *diki.ReportOutputSpec, out *ReportOutputSpec, s conversion.Scope) error {
	if err := Convert_diki_Output_To_v1alpha1_Output(&in.Output, &out.Output, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_ReportOutputSpec_To_v1alpha1_ReportOutputSpec is an autogenerated conversion function.
func Convert_diki_ReportOutputSpec_To_v1alpha1_ReportOutputSpec(in *diki.ReportOutputSpec, out *ReportOutputSpec, s conversion.Scope) error {
	return autoConvert_diki_ReportOutputSpec_To_v1alpha1_ReportOutputSpec(in, out, s)
}

func autoConvert_v1alpha1_Rule_To_diki_Rule(in *Rule, out *diki.Rule, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_Rule_To_diki_Rule is an autogenerated conversion function.
func Convert_v1alpha1_Rule_To_diki_Rule(in *Rule, out *diki.Rule, s conversion.Scope) error {
	return autoConvert_v1alpha1_Rule_To_diki_Rule(in, out, s)
}

func autoConvert_diki_Rule_To_v1alpha1_Rule(in *diki.Rule, out *Rule, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_diki_Rule_To_v1alpha1_Rule is an autogenerated conversion function.
func Convert_diki_Rule_To_v1alpha1_Rule(in *diki.Rule, out *Rule, s conversion.Scope) error {
	return autoConvert_diki_Rule_To_v1alpha1_Rule(in, out, s)
}

func autoConvert_v1alpha1_RulesFindings_To_diki_RulesFindings(in *RulesFindings, out *diki.RulesFindings, s conversion.Scope) error {
	out.Failed = *(*[]diki.Rule)(unsafe.Pointer(&in.Failed))
	out.Errored = *(*[]diki.Rule)(unsafe.Pointer(&in.Errored))
	out.Warning = *(*[]diki.Rule)(unsafe.Pointer(&in.Warning))
	return nil
}

// Convert_v1alpha1_RulesFindings_To_diki_RulesFindings is an autogenerated conversion function.
func Convert_v1alpha1_RulesFindings_To_diki_RulesFindings(in *RulesFindings, out *diki.RulesFindings, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesFindings_To_diki_RulesFindings(in, out, s)
}

func autoConvert_diki_RulesFindings_To_v1alpha1_RulesFindings(in *diki.RulesFindings, out *RulesFindings, s conversion.Scope) error {
	out.Failed = *(*[]Rule)(unsafe.Pointer(&in.Failed))
	out.Errored = *(*[]Rule)(unsafe.Pointer(&in.Errored))
	out.Warning = *(*[]Rule)(unsafe.Pointer(&in.Warning))
	return nil
}

// Convert_diki_RulesFindings_To_v1alpha1_RulesFindings is an autogenerated conversion function.
func Convert_diki_RulesFindings_To_v1alpha1_RulesFindings(in *diki.RulesFindings, out *RulesFindings, s conversion.Scope) error {
	return autoConvert_diki_RulesFindings_To_v1alpha1_RulesFindings(in, out, s)
}

func autoConvert_v1alpha1_RulesResults_To_diki_RulesResults(in *RulesResults, out *diki.RulesResults, s conversion.Scope) error {
	if err := Convert_v1alpha1_RulesSummary_To_diki_RulesSummary(&in.Summary, &out.Summary, s); err != nil {
		return err
	}
	out.Rules = (*diki.RulesFindings)(unsafe.Pointer(in.Rules))
	return nil
}

// Convert_v1alpha1_RulesResults_To_diki_RulesResults is an autogenerated conversion function.
func Convert_v1alpha1_RulesResults_To_diki_RulesResults(in *RulesResults, out *diki.RulesResults, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesResults_To_diki_RulesResults(in, out, s)
}

func autoConvert_diki_RulesResults_To_v1alpha1_RulesResults(in *diki.RulesResults, out *RulesResults, s conversion.Scope) error {
	if err := Convert_diki_RulesSummary_To_v1alpha1_RulesSummary(&in.Summary, &out.Summary, s); err != nil {
		return err
	}
	out.Rules = (*RulesFindings)(unsafe.Pointer(in.Rules))
	return nil
}

// Convert_diki_RulesResults_To_v1alpha1_RulesResults is an autogenerated conversion function.
func Convert_diki_RulesResults_To_v1alpha1_RulesResults(in *diki.RulesResults, out *RulesResults, s conversion.Scope) error {
	return autoConvert_diki_RulesResults_To_v1alpha1_RulesResults(in, out, s)
}

func autoConvert_v1alpha1_RulesSummary_To_diki_RulesSummary(in *RulesSummary, out *diki.RulesSummary, s conversion.Scope) error {
	out.Passed = in.Passed
	out.Skipped = in.Skipped
	out.Accepted = in.Accepted
	out.Warning = in.Warning
	out.Failed = in.Failed
	out.Errored = in.Errored
	return nil
}

// Convert_v1alpha1_RulesSummary_To_diki_RulesSummary is an autogenerated conversion function.
func Convert_v1alpha1_RulesSummary_To_diki_RulesSummary(in *RulesSummary, out *diki.RulesSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesSummary_To_diki_RulesSummary(in, out, s)
}

func autoConvert_diki_RulesSummary_To_v1alpha1_RulesSummary(in *diki.RulesSummary, out *RulesSummary, s conversion.Scope) error {
	out.Passed = in.Passed
	out.Skipped = in.Skipped
	out.Accepted = in.Accepted
	out.Warning = in.Warning
	out.Failed = in.Failed
	out.Errored = in.Errored
	return nil
}

// Convert_diki_RulesSummary_To_v1alpha1_RulesSummary is an autogenerated conversion function.
func Convert_diki_RulesSummary_To_v1alpha1_RulesSummary(in *diki.RulesSummary, out *RulesSummary, s conversion.Scope) error {
	return autoConvert_diki_RulesSummary_To_v1alpha1_RulesSummary(in, out, s)
}

func autoConvert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(in *RulesetConfig, out *diki.RulesetConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	out.Options = (*diki.RulesetOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1alpha1_RulesetConfig_To_diki_RulesetConfig is an autogenerated conversion function.
func Convert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(in *RulesetConfig, out *diki.RulesetConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(in, out, s)
}

func autoConvert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(in *diki.RulesetConfig, out *RulesetConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	out.Options = (*RulesetOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_diki_RulesetConfig_To_v1alpha1_RulesetConfig is an autogenerated conversion function.
func Convert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(in *diki.RulesetConfig, out *RulesetConfig, s conversion.Scope) error {
	return autoConvert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(in, out, s)
}

func autoConvert_v1alpha1_RulesetOptions_To_diki_RulesetOptions(in *RulesetOptions, out *diki.RulesetOptions, s conversion.Scope) error {
	out.Ruleset = (*diki.Options)(unsafe.Pointer(in.Ruleset))
	out.Rules = (*diki.Options)(unsafe.Pointer(in.Rules))
	return nil
}

// Convert_v1alpha1_RulesetOptions_To_diki_RulesetOptions is an autogenerated conversion function.
func Convert_v1alpha1_RulesetOptions_To_diki_RulesetOptions(in *RulesetOptions, out *diki.RulesetOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesetOptions_To_diki_RulesetOptions(in, out, s)
}

func autoConvert_diki_RulesetOptions_To_v1alpha1_RulesetOptions(in *diki.RulesetOptions, out *RulesetOptions, s conversion.Scope) error {
	out.Ruleset = (*Options)(unsafe.Pointer(in.Ruleset))
	out.Rules = (*Options)(unsafe.Pointer(in.Rules))
	return nil
}

// Convert_diki_RulesetOptions_To_v1alpha1_RulesetOptions is an autogenerated conversion function.
func Convert_diki_RulesetOptions_To_v1alpha1_RulesetOptions(in *diki.RulesetOptions, out *RulesetOptions, s conversion.Scope) error {
	return autoConvert_diki_RulesetOptions_To_v1alpha1_RulesetOptions(in, out, s)
}

func autoConvert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(in *RulesetSummary, out *diki.RulesetSummary, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	if err := Convert_v1alpha1_RulesResults_To_diki_RulesResults(&in.Results, &out.Results, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RulesetSummary_To_diki_RulesetSummary is an autogenerated conversion function.
func Convert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(in *RulesetSummary, out *diki.RulesetSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(in, out, s)
}

func autoConvert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(in *diki.RulesetSummary, out *RulesetSummary, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	if err := Convert_diki_RulesResults_To_v1alpha1_RulesResults(&in.Results, &out.Results, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_RulesetSummary_To_v1alpha1_RulesetSummary is an autogenerated conversion function.
func Convert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(in *diki.RulesetSummary, out *RulesetSummary, s conversion.Scope) error {
	return autoConvert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(in, out, s)
}

func autoConvert_v1alpha1_ScheduledComplianceScan_To_diki_ScheduledComplianceScan(in *ScheduledComplianceScan, out *diki.ScheduledComplianceScan, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ScheduledComplianceScanSpec_To_diki_ScheduledComplianceScanSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ScheduledComplianceScanStatus_To_diki_ScheduledComplianceScanStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ScheduledComplianceScan_To_diki_ScheduledComplianceScan is an autogenerated conversion function.
func Convert_v1alpha1_ScheduledComplianceScan_To_diki_ScheduledComplianceScan(in *ScheduledComplianceScan, out *diki.ScheduledComplianceScan, s conversion.Scope) error {
	return autoConvert_v1alpha1_ScheduledComplianceScan_To_diki_ScheduledComplianceScan(in, out, s)
}

func autoConvert_diki_ScheduledComplianceScan_To_v1alpha1_ScheduledComplianceScan(in *diki.ScheduledComplianceScan, out *ScheduledComplianceScan, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_diki_ScheduledComplianceScanSpec_To_v1alpha1_ScheduledComplianceScanSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_diki_ScheduledComplianceScanStatus_To_v1alpha1_ScheduledComplianceScanStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_ScheduledComplianceScan_To_v1alpha1_ScheduledComplianceScan is an autogenerated conversion function.
func Convert_diki_ScheduledComplianceScan_To_v1alpha1_ScheduledComplianceScan(in *diki.ScheduledComplianceScan, out *ScheduledComplianceScan, s conversion.Scope) error {
	return autoConvert_diki_ScheduledComplianceScan_To_v1alpha1_ScheduledComplianceScan(in, out, s)
}

func autoConvert_v1alpha1_ScheduledComplianceScanList_To_diki_ScheduledComplianceScanList(in *ScheduledComplianceScanList, out *diki.ScheduledComplianceScanList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]diki.ScheduledComplianceScan)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ScheduledComplianceScanList_To_diki_ScheduledComplianceScanList is an autogenerated conversion function.
func Convert_v1alpha1_ScheduledComplianceScanList_To_diki_ScheduledComplianceScanList(in *ScheduledComplianceScanList, out *diki.ScheduledComplianceScanList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ScheduledComplianceScanList_To_diki_ScheduledComplianceScanList(in, out, s)
}

func autoConvert_diki_ScheduledComplianceScanList_To_v1alpha1_ScheduledComplianceScanList(in *diki.ScheduledComplianceScanList, out *ScheduledComplianceScanList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ScheduledComplianceScan)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_diki_ScheduledComplianceScanList_To_v1alpha1_ScheduledComplianceScanList is an autogenerated conversion function.
func Convert_diki_ScheduledComplianceScanList_To_v1alpha1_ScheduledComplianceScanList(in *diki.ScheduledComplianceScanList, out *ScheduledComplianceScanList, s conversion.Scope) error {
	return autoConvert_diki_ScheduledComplianceScanList_To_v1alpha1_ScheduledComplianceScanList(in, out, s)
}

func autoConvert_v1alpha1_ScheduledComplianceScanSpec_To_diki_ScheduledComplianceScanSpec(in *ScheduledComplianceScanSpec, out *diki.ScheduledComplianceScanSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	out.RunsHistoryLimit = (*int32)(unsafe.Pointer(in.RunsHistoryLimit))
	if err := Convert_v1alpha1_ComplianceScanTemplate_To_diki_ComplianceScanTemplate(&in.RunTemplate, &out.RunTemplate, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ScheduledComplianceScanSpec_To_diki_ScheduledComplianceScanSpec is an autogenerated conversion function.
func Convert_v1alpha1_ScheduledComplianceScanSpec_To_diki_ScheduledComplianceScanSpec(in *ScheduledComplianceScanSpec, out *diki.ScheduledComplianceScanSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ScheduledComplianceScanSpec_To_diki_ScheduledComplianceScanSpec(in, out, s)
}

func autoConvert_diki_ScheduledComplianceScanSpec_To_v1alpha1_ScheduledComplianceScanSpec(in *diki.ScheduledComplianceScanSpec, out *ScheduledComplianceScanSpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	out.RunsHistoryLimit = (*int32)(unsafe.Pointer(in.RunsHistoryLimit))
	if err := Convert_diki_ComplianceScanTemplate_To_v1alpha1_ComplianceScanTemplate(&in.RunTemplate, &out.RunTemplate, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_ScheduledComplianceScanSpec_To_v1alpha1_ScheduledComplianceScanSpec is an autogenerated conversion function.
func Convert_diki_ScheduledComplianceScanSpec_To_v1alpha1_ScheduledComplianceScanSpec(in *diki.ScheduledComplianceScanSpec, out *ScheduledComplianceScanSpec, s conversion.Scope) error {
	return autoConvert_diki_ScheduledComplianceScanSpec_To_v1alpha1_ScheduledComplianceScanSpec(in, out, s)
}

func autoConvert_v1alpha1_ScheduledComplianceScanStatus_To_diki_ScheduledComplianceScanStatus(in *ScheduledComplianceScanStatus, out *diki.ScheduledComplianceScanStatus, s conversion.Scope) error {
	out.Active = (*v1.ObjectReference)(unsafe.Pointer(in.Active))
	out.LastScheduleTime = (*metav1.Time)(unsafe.Pointer(in.LastScheduleTime))
	out.LastCompletionTime = (*metav1.Time)(unsafe.Pointer(in.LastCompletionTime))
	return nil
}

// Convert_v1alpha1_ScheduledComplianceScanStatus_To_diki_ScheduledComplianceScanStatus is an autogenerated conversion function.
func Convert_v1alpha1_ScheduledComplianceScanStatus_To_diki_ScheduledComplianceScanStatus(in *ScheduledComplianceScanStatus, out *diki.ScheduledComplianceScanStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ScheduledComplianceScanStatus_To_diki_ScheduledComplianceScanStatus(in, out, s)
}

func autoConvert_diki_ScheduledComplianceScanStatus_To_v1alpha1_ScheduledComplianceScanStatus(in *diki.ScheduledComplianceScanStatus, out *ScheduledComplianceScanStatus, s conversion.Scope) error {
	out.Active = (*v1.ObjectReference)(unsafe.Pointer(in.Active))
	out.LastScheduleTime = (*metav1.Time)(unsafe.Pointer(in.LastScheduleTime))
	out.LastCompletionTime = (*metav1.Time)(unsafe.Pointer(in.LastCompletionTime))
	return nil
}

// Convert_diki_ScheduledComplianceScanStatus_To_v1alpha1_ScheduledComplianceScanStatus is an autogenerated conversion function.
func Convert_diki_ScheduledComplianceScanStatus_To_v1alpha1_ScheduledComplianceScanStatus(in *diki.ScheduledComplianceScanStatus, out *ScheduledComplianceScanStatus, s conversion.Scope) error {
	return autoConvert_diki_ScheduledComplianceScanStatus_To_v1alpha1_ScheduledComplianceScanStatus(in, out, s)
}
